spring.application.name=usuario

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource Configuration (In-memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver